/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Control;
import javax.swing.JOptionPane;

/**
 *
 * @author ilope
 */
public class frmAlarmaBloqueo extends javax.swing.JFrame {
      private Control control;
    /**
     * Creates new form frmAlarmaBloqueo
     */
    public frmAlarmaBloqueo(Control control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlarma = new javax.swing.JToggleButton();
        btnBloqueo = new javax.swing.JToggleButton();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alarmaAuto.png"))); // NOI18N
        btnAlarma.setText("jToggleButton2");
        btnAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlarmaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, 80));

        btnBloqueo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/puerta.png"))); // NOI18N
        btnBloqueo.setText("jToggleButton1");
        btnBloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqueoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBloqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 110, 80));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 90, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Control de Alarma y Bloqueo");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlarmaActionPerformed
         boolean activar = btnAlarma.isSelected();
            control.activarAlarma(activar);
            btnAlarma.setText(activar ? "Desactivar Alarma" : "Activar Alarma");
            JOptionPane.showMessageDialog(this, activar ? "Alarma activada." : "Alarma desactivada.");
    }//GEN-LAST:event_btnAlarmaActionPerformed

    private void btnBloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqueoActionPerformed
        boolean bloquear = btnBloqueo.isSelected();
            control.bloquearPuertas(bloquear);
            btnBloqueo.setText(bloquear ? "Desbloquear Puertas" : "Bloquear Puertas");
            JOptionPane.showMessageDialog(this, bloquear ? "Puertas bloqueadas." : "Puertas desbloqueadas.");
    }//GEN-LAST:event_btnBloqueoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlarma;
    private javax.swing.JToggleButton btnBloqueo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
