/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista;


import Controlador.Control;


/**
 *
 * @author ilope
 */
public class FrmCinturones extends javax.swing.JFrame {
 private Control control;

    public FrmCinturones(Control control) {
        this.control = control;
        initComponents();
        sincronizarEstado();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPasajero = new javax.swing.JToggleButton();
        btnPiloto = new javax.swing.JToggleButton();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPasajero.setBackground(new java.awt.Color(0, 0, 0));
        btnPasajero.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPasajero.setText("Pasajero");
        btnPasajero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasajeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, 80));

        btnPiloto.setBackground(new java.awt.Color(0, 0, 0));
        btnPiloto.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPiloto.setText("Piloto");
        btnPiloto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, 80));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 90, 50));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cinturones de Seguridad");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 40));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Piloto");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 60, 20));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Pasajeros");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void sincronizarEstado() {
        btnPiloto.setSelected(control.isCinturonPiloto());
        btnPiloto.setText(control.isCinturonPiloto() ? "Piloto: Abrochado" : "Piloto: No abrochado");

        btnPasajero.setSelected(control.isCinturonPasajero());
        btnPasajero.setText(control.isCinturonPasajero() ? "Pasajero: Abrochado" : "Pasajero: No abrochado");
    }
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilotoActionPerformed
        toggleCinturonPiloto();
    }//GEN-LAST:event_btnPilotoActionPerformed

    private void btnPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajeroActionPerformed
        toggleCinturonPasajero();
    }//GEN-LAST:event_btnPasajeroActionPerformed
    private void toggleCinturonPiloto() {
        boolean abrochado = btnPiloto.isSelected();
        control.setCinturonPiloto(abrochado);
        btnPiloto.setText(abrochado ? "Piloto: Abrochado" : "Piloto: No abrochado");
    }
    
    private void toggleCinturonPasajero() {
        boolean abrochado = btnPasajero.isSelected();
        control.setCinturonPasajero(abrochado);
        btnPasajero.setText(abrochado ? "Pasajero: Abrochado" : "Pasajero: No abrochado");
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPasajero;
    private javax.swing.JToggleButton btnPiloto;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
