/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Control;
import Enums.EstadoClimatizado;
import Enums.EstadoEncendido;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author huete
 */
public class FrmClimatizacion extends javax.swing.JFrame {
        private Control control;
        private EstadoClimatizado[] niveles = EstadoClimatizado.values();
        private int indiceVelocidad =0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmClimatizacion.class.getName());

    /**
     * Creates new form FrmClimatizacion
     */
    public FrmClimatizacion() {
        initComponents();
        control = new Control(4,5);
        BtnAC.addActionListener(new java.awt.event.ActionListener() {
            private boolean ACEncendida = false;
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               if (!ACEncendida) {
            control.activarCalefaccion(true);
            control.activarAC(false); // Apaga el aire acondicionado
            JOptionPane.showMessageDialog(null, "Calefacción activada");
            ACEncendida = true;
        } else {
            control.activarCalefaccion(true);
            JOptionPane.showMessageDialog(null, "Calefacción apagada");
            ACEncendida = false;
        }
            }
        });
         BtnCalefaccion.addActionListener(new java.awt.event.ActionListener() {
             private boolean calefaccionEncendida = false;
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              if (!calefaccionEncendida) {
            control.activarCalefaccion(true);
            control.activarAC(false); // Apaga el aire acondicionado
            JOptionPane.showMessageDialog(null, "Calefacción activada");
            calefaccionEncendida = true;
        } else {
            control.activarCalefaccion(true);
            JOptionPane.showMessageDialog(null, "Calefacción apagada");
            calefaccionEncendida = false;
        }
            }
         });
         BtnMas.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 if (indiceVelocidad < niveles.length - 1){
                     indiceVelocidad++;
                     EstadoClimatizado nuevaVelocidad = niveles[indiceVelocidad];
                     control.cambiarVelocidadClimatizacion(nuevaVelocidad);
                     VarNivel.setText(nuevaVelocidad.toString());
                 }
            }
         });
         BtnMenos.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               if (indiceVelocidad > 0){
                  indiceVelocidad--;
                  EstadoClimatizado nuevaVelocidad = niveles[indiceVelocidad];
                  control.cambiarVelocidadClimatizacion(nuevaVelocidad);
                  VarNivel.setText(nuevaVelocidad.toString());
                  
               }
            }
         });
        Encender.addActionListener(new java.awt.event.ActionListener() {
            private boolean aireEncendido = false;
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               if (!aireEncendido) {
            control.activarAC(true);
            aireEncendido = true;
            JOptionPane.showMessageDialog(null, "Aire  encendido");
        } else {
            control.activarAC(false);
            aireEncendido = false;
            JOptionPane.showMessageDialog(null, "Aire  apagado");
        }
            }
        });
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        BtnAC = new javax.swing.JButton();
        BtnCalefaccion = new javax.swing.JButton();
        BtnMas = new javax.swing.JButton();
        BtnMenos = new javax.swing.JButton();
        Velocidades = new javax.swing.JLabel();
        VarNivel = new javax.swing.JLabel();
        Encender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(0, 0, 0));
        JPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanel.setForeground(new java.awt.Color(0, 0, 153));

        BtnAC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAC.setForeground(new java.awt.Color(0, 0, 0));
        BtnAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aire-acondicionado_32.png"))); // NOI18N
        BtnAC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aire-acondicionado_64.png"))); // NOI18N
        BtnAC.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aire-acondicionado_64.png"))); // NOI18N
        BtnAC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnACMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnACMouseExited(evt);
            }
        });
        BtnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnACActionPerformed(evt);
            }
        });

        BtnCalefaccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCalefaccion.setForeground(new java.awt.Color(0, 0, 0));
        BtnCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calefaccion_32.png"))); // NOI18N
        BtnCalefaccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCalefaccion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calefaccion_64.png"))); // NOI18N
        BtnCalefaccion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calefaccion_64.png"))); // NOI18N
        BtnCalefaccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCalefaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCalefaccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCalefaccionMouseExited(evt);
            }
        });

        BtnMas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMas.setForeground(new java.awt.Color(0, 0, 0));
        BtnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        BtnMas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMasMouseExited(evt);
            }
        });

        BtnMenos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boton-menos.png"))); // NOI18N
        BtnMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMenos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMenosMouseExited(evt);
            }
        });

        Velocidades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Velocidades.setForeground(new java.awt.Color(255, 255, 255));
        Velocidades.setText("Velocidad:");

        VarNivel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VarNivel.setForeground(new java.awt.Color(255, 255, 255));

        Encender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/encendido-apagado.png"))); // NOI18N
        Encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(BtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Encender, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCalefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(VarNivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades)
                            .addComponent(VarNivel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addComponent(Encender)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCalefaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnACMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnACMouseEntered
        BtnAC.setText("AC");
    }//GEN-LAST:event_BtnACMouseEntered

    private void BtnCalefaccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalefaccionMouseEntered
        BtnCalefaccion.setText("Calefacción");
    }//GEN-LAST:event_BtnCalefaccionMouseEntered

    private void BtnCalefaccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalefaccionMouseExited
        BtnCalefaccion.setText("");
    }//GEN-LAST:event_BtnCalefaccionMouseExited

    private void BtnACMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnACMouseExited
        BtnAC.setText("");
    }//GEN-LAST:event_BtnACMouseExited

    private void BtnMasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMasMouseEntered
        BtnMas.setText("Subir");
    }//GEN-LAST:event_BtnMasMouseEntered

    private void BtnMenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenosMouseEntered
        BtnMenos.setText("Bajar");
    }//GEN-LAST:event_BtnMenosMouseEntered

    private void BtnMasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMasMouseExited
        BtnMas.setText("");
    }//GEN-LAST:event_BtnMasMouseExited

    private void BtnMenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenosMouseExited
          BtnMenos.setText("");
    }//GEN-LAST:event_BtnMenosMouseExited

    private void EncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncenderActionPerformed

    private void BtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnACActionPerformed
    private String formatoVelocidad(EstadoClimatizado vel){
        return switch (vel){
            case APAGADO -> "Apagado";
            case BAJA -> "Baja";
            case MEDIA -> "Media";
            case ALTA -> "Alta";
        };
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmClimatizacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAC;
    private javax.swing.JButton BtnCalefaccion;
    private javax.swing.JButton BtnMas;
    private javax.swing.JButton BtnMenos;
    private javax.swing.JButton Encender;
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel VarNivel;
    private javax.swing.JLabel Velocidades;
    // End of variables declaration//GEN-END:variables
}
