/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Control;
import Enums.EstadoClimatizado;
import javax.swing.JOptionPane;


/**
 *
 * @author huete
 */
public class FrmClimatizacion extends javax.swing.JFrame {
        private Control control;
    private EstadoClimatizado[] velocidades = EstadoClimatizado.values();
    private int indiceVelocidad = 0; // Empieza en APAGADO

    public FrmClimatizacion(Control control) {
        this.control = control;
        initComponents();
        sincronizarEstado();
    }
    private void sincronizarEstado() {
        boolean activo = control.getVelocidadClimatizacion() != EstadoClimatizado.APAGADO;
        toggleClima.setSelected(activo);
        toggleClima.setText(activo ? "Apagar" : "Encender");

        if (control.getVelocidadClimatizacion() != null) {
            indiceVelocidad = control.getVelocidadClimatizacion().ordinal();
        }

        actualizarEtiquetaEstado();
    }

    private void actualizarEtiquetaEstado() {
        EstadoClimatizado velocidad = control.getVelocidadClimatizacion();
        String modo = control.isACActivo() ? "A/C" : control.isCalefaccionActiva() ? "Calefacción" : "Apagado";
        lblEstado.setText("Modo: " + modo + ", Velocidad: " + velocidad);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        toggleClima = new javax.swing.JToggleButton();
        btnCalefaccion = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnAumentar = new javax.swing.JButton();
        btnDisminuir = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Climatizacion");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 130, 50));

        toggleClima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/encendido-apagado.png"))); // NOI18N
        toggleClima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleClimaActionPerformed(evt);
            }
        });
        getContentPane().add(toggleClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 40, 40));

        btnCalefaccion.setBackground(new java.awt.Color(255, 102, 51));
        btnCalefaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calefaccion_32.png"))); // NOI18N
        btnCalefaccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true));
        btnCalefaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalefaccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalefaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 60));

        btnAC.setBackground(new java.awt.Color(0, 0, 0));
        btnAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aire-acondicionado_32.png"))); // NOI18N
        btnAC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });
        getContentPane().add(btnAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 90, 60));

        btnAumentar.setBackground(new java.awt.Color(0, 153, 0));
        btnAumentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        btnAumentar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));
        btnAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 40, 40));

        btnDisminuir.setBackground(new java.awt.Color(153, 0, 0));
        btnDisminuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boton-menos.png"))); // NOI18N
        btnDisminuir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        btnDisminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 40, 40));

        lblEstado.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 300, 30));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Velocidad del Climatizado");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Calefaccion |   A/C");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 30));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalefaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalefaccionActionPerformed
        activarCalefaccion();
    }//GEN-LAST:event_btnCalefaccionActionPerformed

    private void toggleClimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleClimaActionPerformed
        if (!control.permiteClimatizacion()) {
            JOptionPane.showMessageDialog(this, "El auto debe estar encendido para usar la climatización.");
            toggleClima.setSelected(false);
            return;
        }

        if (toggleClima.isSelected()) {
            // Activar A/C por defecto
            control.activarAC(true);
            indiceVelocidad = EstadoClimatizado.BAJA.ordinal();
            control.cambiarVelocidadClimatizacion(EstadoClimatizado.BAJA);
            toggleClima.setText("Apagar");
        } else {
            control.apagarClimatizacion();
            indiceVelocidad = 0;
            toggleClima.setText("Encender");
        }
        actualizarEtiquetaEstado();
    }//GEN-LAST:event_toggleClimaActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        activarAC();
    }//GEN-LAST:event_btnACActionPerformed

    private void btnDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirActionPerformed
       cambiarVelocidad(-1);
    }//GEN-LAST:event_btnDisminuirActionPerformed

    private void btnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarActionPerformed
       cambiarVelocidad(1);
    }//GEN-LAST:event_btnAumentarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    
    private void cambiarVelocidad(int cambio) {
        if (!control.permiteClimatizacion()) {
            JOptionPane.showMessageDialog(this, "Auto apagado. No se puede cambiar la velocidad.");
            return;
        }

        if (!toggleClima.isSelected()) {
            JOptionPane.showMessageDialog(this, "Primero enciende la climatización.");
            return;
        }

        indiceVelocidad = Math.max(1, Math.min(indiceVelocidad + cambio, velocidades.length - 1));
        control.cambiarVelocidadClimatizacion(velocidades[indiceVelocidad]);
        actualizarEtiquetaEstado();
    }

    private void activarAC() {
        if (!control.permiteClimatizacion()) {
            JOptionPane.showMessageDialog(this, "Auto apagado. No se puede activar A/C.");
            return;
        }
        control.activarAC(true);
        control.cambiarVelocidadClimatizacion(velocidades[indiceVelocidad == 0 ? 1 : indiceVelocidad]);
        toggleClima.setSelected(true);
        toggleClima.setText("Apagar");
        actualizarEtiquetaEstado();
    }

    private void activarCalefaccion() {
        if (!control.permiteClimatizacion()) {
            JOptionPane.showMessageDialog(this, "Auto apagado. No se puede activar calefacción.");
            return;
        }
        control.activarCalefaccion(true);
        control.cambiarVelocidadClimatizacion(velocidades[indiceVelocidad == 0 ? 1 : indiceVelocidad]);
        toggleClima.setSelected(true);
        toggleClima.setText("Apagar");
        actualizarEtiquetaEstado();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAumentar;
    private javax.swing.JButton btnCalefaccion;
    private javax.swing.JButton btnDisminuir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JToggleButton toggleClima;
    // End of variables declaration//GEN-END:variables
}
