/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista;


import modelo.sistemaCinturones;

/**
 *
 * @author LOLO
 */
public class FrmCinturones extends javax.swing.JFrame {
 sistemaCinturones sistema;

    /** Creates new form FrmCinturones */
    public FrmCinturones() {
        initComponents();
       sistema = new sistemaCinturones(1);
lblEstadoCinturon.setText("Estado: " + (sistema.estaAbrochado() ? "Abrochado" : "No Abrochado"));


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEstado = new javax.swing.JButton();
        JLabelEstado = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblEstadoCinturon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cinturon-de-seguridad-para-el-conductor (2).png"))); // NOI18N
        jLabelEstado.setText("Abrochar");
        jLabelEstado.setIconTextGap(7);
        jLabelEstado.setMaximumSize(new java.awt.Dimension(100, 519));
        jLabelEstado.setMinimumSize(new java.awt.Dimension(100, 519));
        jLabelEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, 80));

        JLabelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/desabrochado.png"))); // NOI18N
        JLabelEstado.setText("Desabrochar");
        JLabelEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLabelEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(JLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 150, 80));

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        lblEstadoCinturon.setText("Estado");
        getContentPane().add(lblEstadoCinturon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelEstadoActionPerformed
        jLabelEstado.setText("Estado: Abrochado");
        sistema.abrocharCinturon();
lblEstadoCinturon.setText("Estado: Abrochado");
    }//GEN-LAST:event_jLabelEstadoActionPerformed

    private void JLabelEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLabelEstadoActionPerformed
       jLabelEstado.setText("Estado: No Abrochado");
       sistema.desabrocharCinturon();
lblEstadoCinturon.setText("Estado: No Abrochado");
    }//GEN-LAST:event_JLabelEstadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCinturones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCinturones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCinturones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCinturones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCinturones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JLabelEstado;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLabelEstado;
    private javax.swing.JLabel lblEstadoCinturon;
    // End of variables declaration//GEN-END:variables

}
