/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Control;
import Enums.EstadoPuerta;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ilope
 */
public class FrmPuerta extends javax.swing.JFrame {
private Control control;
    /**
     * Creates new form FrmPuertas
     */
    public FrmPuerta(Control control) {
        this.control = control;
        initComponents();
        configurarBotones();
        actualizarEstados();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPuerta0 = new javax.swing.JToggleButton();
        btnPuerta1 = new javax.swing.JToggleButton();
        btnPuerta2 = new javax.swing.JToggleButton();
        btnPuerta3 = new javax.swing.JToggleButton();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPuerta0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/puertasCerradas.png"))); // NOI18N
        btnPuerta0.setText("jToggleButton1");
        btnPuerta0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuerta0, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 120, 135, 170));

        btnPuerta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/puertasCerradas.png"))); // NOI18N
        btnPuerta1.setText("jToggleButton1");
        btnPuerta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 130, 170));

        btnPuerta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/puertasCerradas.png"))); // NOI18N
        btnPuerta2.setText("jToggleButton1");
        btnPuerta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuerta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 335, 135, 170));

        btnPuerta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/puertasCerradas.png"))); // NOI18N
        btnPuerta3.setText("jToggleButton1");
        btnPuerta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuerta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 130, 170));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 90, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Control de Puertas");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPuerta0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta0ActionPerformed
        togglePuerta(0, btnPuerta0);
    }//GEN-LAST:event_btnPuerta0ActionPerformed

    private void btnPuerta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta2ActionPerformed
        togglePuerta(2, btnPuerta2);
    }//GEN-LAST:event_btnPuerta2ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnPuerta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta1ActionPerformed
        togglePuerta(1, btnPuerta1);
    }//GEN-LAST:event_btnPuerta1ActionPerformed

    private void btnPuerta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta3ActionPerformed
        togglePuerta(3, btnPuerta3);
    }//GEN-LAST:event_btnPuerta3ActionPerformed
    private void configurarBotones() {
        // Imágenes de las puertas
        ImageIcon iconCerrada = new ImageIcon(getClass().getResource("/Images/puertasCerradas.png"));
        ImageIcon iconAbierta = new ImageIcon(getClass().getResource("/Images/puertasAbiertas.png"));

        // Asignar imágenes por estado
        configurarBoton(btnPuerta0, iconCerrada, iconAbierta);
        configurarBoton(btnPuerta1, iconCerrada, iconAbierta);
        configurarBoton(btnPuerta2, iconCerrada, iconAbierta);
        configurarBoton(btnPuerta3, iconCerrada, iconAbierta);
    }
    private void configurarBoton(javax.swing.JToggleButton boton, ImageIcon iconCerrada, ImageIcon iconAbierta) {
        boton.setIcon(iconCerrada);
        boton.setSelectedIcon(iconAbierta);
        boton.setText(""); // Sin texto
        boton.setBorderPainted(false);
        boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
    }

    private void togglePuerta(int i, javax.swing.JToggleButton boton) {
    EstadoPuerta estado = control.getEstadoPuerta(i);
    boolean bloqueadas = control.getEstadoPuertasBloqueadas();

    if (bloqueadas && estado == EstadoPuerta.CERRADA) {
        JOptionPane.showMessageDialog(this, "No se puede abrir. Las puertas están bloqueadas.");
        actualizarEstados();
        return;
    }

    if (estado == EstadoPuerta.CERRADA) {
        boolean exito = control.abrirPuerta(i);
        if (!exito) {
            JOptionPane.showMessageDialog(this, "No se pudo abrir la puerta.");
        }
    } else {
        control.cerrarPuerta(i);
    }

    actualizarEstados();
}


    private void actualizarEstados() {
        btnPuerta0.setSelected(control.getEstadoPuerta(0) == EstadoPuerta.ABIERTA);
        btnPuerta1.setSelected(control.getEstadoPuerta(1) == EstadoPuerta.ABIERTA);
        btnPuerta2.setSelected(control.getEstadoPuerta(2) == EstadoPuerta.ABIERTA);
        btnPuerta3.setSelected(control.getEstadoPuerta(3) == EstadoPuerta.ABIERTA);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPuerta0;
    private javax.swing.JToggleButton btnPuerta1;
    private javax.swing.JToggleButton btnPuerta2;
    private javax.swing.JToggleButton btnPuerta3;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
