/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Control;
import Enums.EstadoEncendido;
import Enums.ModoRadio;
import javax.swing.JOptionPane;

/**
 *
 * @author LOLO
 */
public class FrmRadio extends javax.swing.JFrame {

    private final Control control;

    public FrmRadio(Control control) {
        this.control = control;
        initComponents();
        verificarEstadoAuto();
        actualizarEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbModo = new javax.swing.JComboBox<>();
        sldFrecuencia = new javax.swing.JSlider();
        btnEncender = new javax.swing.JToggleButton();
        lblEstado1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbModo.setBackground(new java.awt.Color(0, 0, 0));
        cmbModo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cmbModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "FM", "BLUETOOTH" }));
        cmbModo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        cmbModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 90, 70));

        sldFrecuencia.setBackground(new java.awt.Color(255, 255, 255));
        sldFrecuencia.setMaximum(108);
        sldFrecuencia.setMinimum(80);
        getContentPane().add(sldFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        btnEncender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnencender.png"))); // NOI18N
        btnEncender.setText("jToggleButton1");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncender, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 80));

        lblEstado1.setBackground(new java.awt.Color(0, 0, 0));
        lblEstado1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblEstado1.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado1.setText("Ajustar Frecuencia");
        lblEstado1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(lblEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 40));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 90, 40));

        lblEstado.setBackground(new java.awt.Color(0, 0, 0));
        lblEstado.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 280, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("        Bienvenido al Radio");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 360, 50));

        lblEstado2.setBackground(new java.awt.Color(0, 0, 0));
        lblEstado2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblEstado2.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado2.setText("Seleccionar modo -----  Apagar/Encender");
        lblEstado2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(lblEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        boolean encendido = control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO;
        if (!encendido) {
            JOptionPane.showMessageDialog(this, "El auto está apagado. Enciéndelo para usar la radio.");
            btnEncender.setSelected(false);
            return;
        }

        if (btnEncender.isSelected()) {
            control.encenderRadio();
            btnEncender.setText("Apagar Radio");
        } else {
            control.apagarRadio();
            btnEncender.setText("Encender Radio");
        }

        actualizarEstado();
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void cmbModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModoActionPerformed
        if (btnEncender.isSelected()) {
            String modoSeleccionado = (String) cmbModo.getSelectedItem();
            control.cambiarModoRadio(ModoRadio.valueOf(modoSeleccionado));
            actualizarEtiqueta();
        }

    }//GEN-LAST:event_cmbModoActionPerformed
     private void sldFrecuenciaStateChanged(javax.swing.event.ChangeEvent evt) {
        if (btnEncender.isSelected()) {
            double frecuencia = sldFrecuencia.getValue();
            control.sintonizarRadio(frecuencia);
            actualizarEtiqueta();
        }
    }

    private void actualizarEtiqueta() {
        String modo = cmbModo.getSelectedItem().toString();
        double frecuencia = sldFrecuencia.getValue();
        lblEstado.setText("Modo: " + modo + " | Frecuencia: " + frecuencia + " MHz");
    }

    private void actualizarEstado() {
        boolean radioEncendida = btnEncender.isSelected();
        cmbModo.setEnabled(radioEncendida);
        sldFrecuencia.setEnabled(radioEncendida);
        if (!radioEncendida) {
            lblEstado.setText("Modo: -- | Frecuencia: --");
        }
    }

    private void verificarEstadoAuto() {
        boolean encendido = control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO;
        if (!encendido) {
            btnEncender.setEnabled(false);
            cmbModo.setEnabled(false);
            sldFrecuencia.setEnabled(false);
            JOptionPane.showMessageDialog(this, "El auto está apagado. Enciéndelo para usar la radio.");
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEncender;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JSlider sldFrecuencia;
    // End of variables declaration//GEN-END:variables
}
