/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import modelo.sistemaEncendido;
import modelo.sistemaRadio;

/**
 *
 * @author LOLO
 */
public class FrmRadio extends javax.swing.JFrame {
private sistemaRadio radio;
private sistemaEncendido sistemaEncendido; // si es necesario
    /**
     * Creates new form FrmRadio
     */
    public FrmRadio() {
        initComponents();
            sistemaEncendido = new sistemaEncendido();
        radio = new sistemaRadio(sistemaEncendido);
        actualizarEstado();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnAM = new javax.swing.JButton();
        btnFM = new javax.swing.JButton();
        btnBluetooth = new javax.swing.JButton();
        btnsubir = new javax.swing.JButton();
        btnBajar = new javax.swing.JButton();
        lblEstadoRadio = new javax.swing.JLabel();
        lblModoActual = new javax.swing.JLabel();
        lblFrecuencia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEncender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sensor-encendido.png"))); // NOI18N
        btnEncender.setText("Encender ");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 120, 50));

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sensor-encendido (1).png"))); // NOI18N
        btnApagar.setText("Apagar");
        getContentPane().add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 130, 50));

        btnAM.setText("Modo AM");
        getContentPane().add(btnAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, 50));

        btnFM.setText("Modo FM");
        getContentPane().add(btnFM, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 110, 50));

        btnBluetooth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circulo-bluetooth.png"))); // NOI18N
        btnBluetooth.setText("Modo Bluetooth");
        btnBluetooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBluetoothActionPerformed(evt);
            }
        });
        getContentPane().add(btnBluetooth, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, 50));

        btnsubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/volumen.png"))); // NOI18N
        btnsubir.setText("Subir Frecuencia");
        getContentPane().add(btnsubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 160, 50));

        btnBajar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bajar-volumen.png"))); // NOI18N
        btnBajar.setText("Bajar Frecuencia");
        getContentPane().add(btnBajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 170, 50));

        lblEstadoRadio.setText("Estado");
        getContentPane().add(lblEstadoRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 40, 40));

        lblModoActual.setText("jLabel2");
        getContentPane().add(lblModoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        lblFrecuencia.setText("jLabel2");
        getContentPane().add(lblFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, -1, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
       radio.encender();
actualizarEstado(); // método que actualiza los labels
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnBluetoothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBluetoothActionPerformed
       radio.cambiarModo(ModoRadio.BLUETOOTH);
actualizarEstado();
    }//GEN-LAST:event_btnBluetoothActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAM;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBajar;
    private javax.swing.JButton btnBluetooth;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnFM;
    private javax.swing.JButton btnsubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEstadoRadio;
    private javax.swing.JLabel lblFrecuencia;
    private javax.swing.JLabel lblModoActual;
    // End of variables declaration//GEN-END:variables
}
