/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Control;
import java.awt.Frame;

/**
 *
 * @author ilope
 */
public class FrmSubSistemas extends javax.swing.JFrame {
    private Control control;
    public FrmSubSistemas(Control control) {
    this.control = control;
    initComponents();
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPuertas = new javax.swing.JButton();
        btnCinturones = new javax.swing.JButton();
        btnAlarma = new javax.swing.JButton();
        btnRadio = new javax.swing.JButton();
        btnClimatizacion = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnParabrisas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        Bienvenido a Subsistemas");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 410, 50));

        btnPuertas.setBackground(new java.awt.Color(0, 0, 0));
        btnPuertas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPuertas.setForeground(new java.awt.Color(255, 255, 255));
        btnPuertas.setText("Puertas");
        btnPuertas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuertasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 70));

        btnCinturones.setBackground(new java.awt.Color(0, 0, 0));
        btnCinturones.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnCinturones.setForeground(new java.awt.Color(255, 255, 255));
        btnCinturones.setText("Cinturones");
        btnCinturones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnCinturones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinturonesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCinturones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 190, 70));

        btnAlarma.setBackground(new java.awt.Color(0, 0, 0));
        btnAlarma.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnAlarma.setForeground(new java.awt.Color(255, 255, 255));
        btnAlarma.setText("Alarma");
        btnAlarma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlarmaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 190, 70));

        btnRadio.setBackground(new java.awt.Color(0, 0, 0));
        btnRadio.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnRadio.setForeground(new java.awt.Color(255, 255, 255));
        btnRadio.setText("Radio");
        btnRadio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 180, 70));

        btnClimatizacion.setBackground(new java.awt.Color(0, 0, 0));
        btnClimatizacion.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnClimatizacion.setForeground(new java.awt.Color(255, 255, 255));
        btnClimatizacion.setText("Climatizacion");
        btnClimatizacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnClimatizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClimatizacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnClimatizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 180, 70));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 180, 50));

        btnParabrisas.setBackground(new java.awt.Color(0, 0, 0));
        btnParabrisas.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnParabrisas.setForeground(new java.awt.Color(255, 255, 255));
        btnParabrisas.setText("Parabrisas");
        btnParabrisas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnParabrisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParabrisasActionPerformed(evt);
            }
        });
        getContentPane().add(btnParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 180, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlarmaActionPerformed
        frmAlarmaBloqueo frame = new frmAlarmaBloqueo(control);
        frame.setVisible(true);
    }//GEN-LAST:event_btnAlarmaActionPerformed

    private void btnPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuertasActionPerformed
        FrmPuerta frmPuerta = new FrmPuerta(control);  
    frmPuerta.setVisible(true);
    }//GEN-LAST:event_btnPuertasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioActionPerformed
        FrmRadio frame = new FrmRadio(control);
        frame.setVisible(true);
    }//GEN-LAST:event_btnRadioActionPerformed

    private void btnCinturonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinturonesActionPerformed
        FrmCinturones frame = new FrmCinturones(control);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCinturonesActionPerformed

    private void btnClimatizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClimatizacionActionPerformed
        FrmClimatizacion frame = new FrmClimatizacion(control);
        frame.setVisible(true);
    }//GEN-LAST:event_btnClimatizacionActionPerformed

    private void btnParabrisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParabrisasActionPerformed
        FrmLimpiaParabrisas frame = new FrmLimpiaParabrisas(control);
        frame.setVisible(true);
    }//GEN-LAST:event_btnParabrisasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlarma;
    private javax.swing.JButton btnCinturones;
    private javax.swing.JButton btnClimatizacion;
    private javax.swing.JButton btnParabrisas;
    private javax.swing.JButton btnPuertas;
    private javax.swing.JButton btnRadio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
