/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Frame;

/**
 *
 * @author ilope
 */
public class FrmSubSistemas extends javax.swing.JFrame {

    /**
     * Creates new form FrmSubSistemas
     */
    public FrmSubSistemas() {
        initComponents();
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPuertas = new javax.swing.JButton();
        btnCinturones = new javax.swing.JButton();
        btnAlarma = new javax.swing.JButton();
        btnRadio = new javax.swing.JButton();
        btnClimatizacion = new javax.swing.JButton();
        btnParabrisas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        Bienvenido a Subsistemas");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 410, 50));

        btnPuertas.setBackground(new java.awt.Color(0, 0, 0));
        btnPuertas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPuertas.setForeground(new java.awt.Color(255, 255, 255));
        btnPuertas.setText("Puertas");
        btnPuertas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(btnPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 70));

        btnCinturones.setBackground(new java.awt.Color(0, 0, 0));
        btnCinturones.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnCinturones.setForeground(new java.awt.Color(255, 255, 255));
        btnCinturones.setText("Cinturones");
        btnCinturones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(btnCinturones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 190, 70));

        btnAlarma.setBackground(new java.awt.Color(0, 0, 0));
        btnAlarma.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnAlarma.setForeground(new java.awt.Color(255, 255, 255));
        btnAlarma.setText("Alarma");
        btnAlarma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(btnAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 190, 70));

        btnRadio.setBackground(new java.awt.Color(0, 0, 0));
        btnRadio.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnRadio.setForeground(new java.awt.Color(255, 255, 255));
        btnRadio.setText("Radio");
        btnRadio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(btnRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 180, 70));

        btnClimatizacion.setBackground(new java.awt.Color(0, 0, 0));
        btnClimatizacion.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnClimatizacion.setForeground(new java.awt.Color(255, 255, 255));
        btnClimatizacion.setText("Climatizacion");
        btnClimatizacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(btnClimatizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 180, 70));

        btnParabrisas.setBackground(new java.awt.Color(0, 0, 0));
        btnParabrisas.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnParabrisas.setForeground(new java.awt.Color(255, 255, 255));
        btnParabrisas.setText("Parabrisas");
        btnParabrisas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        getContentPane().add(btnParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 180, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSubSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSubSistemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlarma;
    private javax.swing.JButton btnCinturones;
    private javax.swing.JButton btnClimatizacion;
    private javax.swing.JButton btnParabrisas;
    private javax.swing.JButton btnPuertas;
    private javax.swing.JButton btnRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
