/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Control;
import Enums.EstadoEncendido;
import Enums.TipoLuz;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.sistemaEnergia;

/**
 *
 * @author Luisk
 */
public class frmVolante extends javax.swing.JFrame {
     private Control control;
     private Timer timerAcelerar;
     private Timer timerFrenar;
     
    
    /**
     * Creates new form frmVolante
     */
    public frmVolante(Control control) {
        this.control = control;
        initComponents();
        sliderVelocidad.setMaximum(220);
        configurarEventos();
        ButtonGroup grupoLuces = new ButtonGroup();
        grupoLuces.add(rbtnApagadas);
        grupoLuces.add(rbtnBajas);
        grupoLuces.add(rbtnAltas);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        sliderVelocidad = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        btnAcelerar = new javax.swing.JButton();
        btnFrenar = new javax.swing.JButton();
        lblVelocidad = new javax.swing.JLabel();
        lblKilometrajeTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        rbtnApagadas = new javax.swing.JRadioButton();
        rbtnBajas = new javax.swing.JRadioButton();
        rbtnAltas = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnEncender = new javax.swing.JToggleButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENERGÍA");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, 40));
        getContentPane().add(sliderVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, 30));

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VELOCIDAD");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, -1));

        btnAcelerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAcelerar.png"))); // NOI18N
        btnAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcelerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 80));

        btnFrenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnFrenar.png"))); // NOI18N
        btnFrenar.setText("frenar");
        btnFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, 80));

        lblVelocidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVelocidad.setText("0");
        getContentPane().add(lblVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 80, 60));

        lblKilometrajeTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKilometrajeTotal.setText("000000");
        getContentPane().add(lblKilometrajeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lblKilometraje.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 200));

        jCheckBox1.setBackground(new java.awt.Color(0, 51, 102));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("ACTIVADO");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox1.setOpaque(true);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 130, 40));

        jLabel7.setBackground(new java.awt.Color(0, 51, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SENSORES:");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 100, 40));

        rbtnApagadas.setBackground(new java.awt.Color(0, 51, 102));
        rbtnApagadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnApagadas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnApagadas.setText("APAGADAS");
        rbtnApagadas.setOpaque(true);
        getContentPane().add(rbtnApagadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        rbtnBajas.setBackground(new java.awt.Color(0, 51, 102));
        rbtnBajas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnBajas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnBajas.setText("BAJAS");
        rbtnBajas.setOpaque(true);
        getContentPane().add(rbtnBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 90, -1));

        rbtnAltas.setBackground(new java.awt.Color(0, 51, 102));
        rbtnAltas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnAltas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAltas.setText("ALTAS");
        rbtnAltas.setOpaque(true);
        getContentPane().add(rbtnAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 90, 30));

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LUCES");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        btnEncender.setBackground(new java.awt.Color(0, 51, 102));
        btnEncender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEncender.setForeground(new java.awt.Color(255, 255, 255));
        btnEncender.setText("Encender motor");
        btnEncender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 140, 30));

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/frmVolante.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarEventos() {
    final boolean[] mensajeMostrado = {false};

    timerAcelerar = new Timer(100, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO && control.getNivelEnergia() > 0) {
                int velocidad = sliderVelocidad.getValue();
                if (velocidad < 220) {
                    velocidad++;
                    sliderVelocidad.setValue(velocidad);
                    lblVelocidad.setText(String.format("%d km/h", velocidad));

                    control.consumirEnergia(0.3);
                    control.actualizarKilometraje(0.05, velocidad, velocidad * 40);

                    int distancia = (int) control.getDistanciaRecorrida();
                    lblKilometrajeTotal.setText(String.format("%05d km", distancia));
                }
            } else {
                if (!mensajeMostrado[0]) {
                    JOptionPane.showMessageDialog(null, "Motor apagado o sin energía.");
                    mensajeMostrado[0] = true;
                }
                timerAcelerar.stop();
            }
        }
    });

    timerFrenar = new Timer(100, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO) {
                int velocidad = sliderVelocidad.getValue();
                if (velocidad > 0) {
                    velocidad--;
                    sliderVelocidad.setValue(velocidad);
                    lblVelocidad.setText(String.format("%d km/h", velocidad));
                    // Ya no se actualiza el kilometraje al frenar
                }
                int distancia = (int) control.getDistanciaRecorrida();
                lblKilometrajeTotal.setText(String.format("%05d km", distancia));
            } else {
                timerFrenar.stop();
            }
        }
    });

    btnAcelerar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO && control.getNivelEnergia() > 0) {
                timerAcelerar.start();
            } else {
                JOptionPane.showMessageDialog(null, "No se puede acelerar. El motor está apagado o sin energía.");
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
            timerAcelerar.stop();
        }
    });

    btnFrenar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            timerFrenar.start();
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
            timerFrenar.stop();
        }
    });
    
  rbtnApagadas.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        if (control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO) {
            control.cambiarLucesDelanteras(TipoLuz.APAGADA);
        } else {
            JOptionPane.showMessageDialog(null, "El vehículo está apagado. No se pueden encender las luces.");
            rbtnApagadas.setSelected(false);
        }
    }
});

rbtnBajas.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        if (control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO) {
            control.cambiarLucesDelanteras(TipoLuz.BAJA);
        } else {
            JOptionPane.showMessageDialog(null, "El vehículo está apagado. No se pueden encender las luces.");
            rbtnBajas.setSelected(false);
        }
    }
});

rbtnAltas.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        if (control.getEstadoEncendido() == EstadoEncendido.ENCENDIDO) {
            control.cambiarLucesDelanteras(TipoLuz.ALTA);
        } else {
            JOptionPane.showMessageDialog(null, "El vehículo está apagado. No se pueden encender las luces.");
            rbtnAltas.setSelected(false);
            }
        }
    });
}
    private void btnAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcelerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcelerarActionPerformed

    private void btnFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFrenarActionPerformed

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        if (btnEncender.isSelected()) {
        control.encenderMotor();
        btnEncender.setText("Apagar");
        // Si querés también podés habilitar aquí el botón de acelerar
        btnAcelerar.setEnabled(true);
    } else {
        control.apagarMotor();
        btnEncender.setText("Encender");
        btnAcelerar.setEnabled(false);
    }
    }//GEN-LAST:event_btnEncenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JToggleButton btnEncender;
    private javax.swing.JButton btnFrenar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblKilometrajeTotal;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JRadioButton rbtnAltas;
    private javax.swing.JRadioButton rbtnApagadas;
    private javax.swing.JRadioButton rbtnBajas;
    private javax.swing.JSlider sliderVelocidad;
    // End of variables declaration//GEN-END:variables
}
