/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Luisk
 */
public class frmVolante extends javax.swing.JFrame {

    /**
     * Creates new form frmVolante
     */
    public frmVolante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        progresoEnergia = new javax.swing.JProgressBar();
        sliderKilometraje = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        btnAcelerar = new javax.swing.JButton();
        btnFrenar = new javax.swing.JButton();
        lblKilometraje = new javax.swing.JLabel();
        lblKilometrajeTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        rbtnApagadas = new javax.swing.JRadioButton();
        rbtnBjas = new javax.swing.JRadioButton();
        rbtnAltas = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENERGÍA");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, 40));

        progresoEnergia.setBackground(new java.awt.Color(255, 255, 255));
        progresoEnergia.setForeground(new java.awt.Color(255, 255, 255));
        progresoEnergia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        progresoEnergia.setBorderPainted(false);
        progresoEnergia.setName(""); // NOI18N
        progresoEnergia.setRequestFocusEnabled(false);
        getContentPane().add(progresoEnergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 140, 30));
        getContentPane().add(sliderKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, 30));

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VELOCIDAD");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, -1));

        btnAcelerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAcelerar.png"))); // NOI18N
        getContentPane().add(btnAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 80));

        btnFrenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnFrenar.png"))); // NOI18N
        btnFrenar.setText("frenar");
        getContentPane().add(btnFrenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, 80));

        lblKilometraje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKilometraje.setText("0");
        getContentPane().add(lblKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 20, 20));

        lblKilometrajeTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKilometrajeTotal.setText("000000");
        getContentPane().add(lblKilometrajeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image (3).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 200));

        jCheckBox1.setBackground(new java.awt.Color(0, 51, 102));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("ACTIVADO");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox1.setOpaque(true);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 130, 40));

        jLabel7.setBackground(new java.awt.Color(0, 51, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SENSORES:");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 100, 40));

        rbtnApagadas.setBackground(new java.awt.Color(0, 51, 102));
        rbtnApagadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnApagadas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnApagadas.setText("APAGADAS");
        rbtnApagadas.setOpaque(true);
        getContentPane().add(rbtnApagadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        rbtnBjas.setBackground(new java.awt.Color(0, 51, 102));
        rbtnBjas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnBjas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnBjas.setText("BAJAS");
        rbtnBjas.setOpaque(true);
        getContentPane().add(rbtnBjas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 90, -1));

        rbtnAltas.setBackground(new java.awt.Color(0, 51, 102));
        rbtnAltas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnAltas.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAltas.setText("ALTAS");
        rbtnAltas.setOpaque(true);
        getContentPane().add(rbtnAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 90, 30));

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LUCES");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/frmVolante.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVolante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVolante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnFrenar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblKilometraje;
    private javax.swing.JLabel lblKilometrajeTotal;
    private javax.swing.JProgressBar progresoEnergia;
    private javax.swing.JRadioButton rbtnAltas;
    private javax.swing.JRadioButton rbtnApagadas;
    private javax.swing.JRadioButton rbtnBjas;
    private javax.swing.JSlider sliderKilometraje;
    // End of variables declaration//GEN-END:variables
}
